name: 'Mobile Build'
description: 'Increase build number of any previous version'
inputs:
  previousVersion:  # id of input
    description: 'Previous version for this build'
    required: true
    default: 'v.1.1.100'
outputs:
  nextVersion: # output will be available to future steps
    description: 'The next version with incremented build number'
runs:
  using: 'node16'
  main: 'dist/index.js'
